language: python
sudo: required

python:
  - "3.7"

env:
  - IBM_POWERAI_LICENSE_ACCEPT=yes

install:
  - sudo apt-get update
  # Install the latest version of Miniconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  # - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda --yes
  # Useful for debugging any issues with conda
  - conda info -a
  - conda config --prepend channels https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/
  - conda config --add channels conda-forge
  - conda config --add channels mlio
  - conda create --yes -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda activate test-environment
  - conda install --file requirements.txt --yes
  - python setup.py install

script:
  # simple train test on small dataset
  - python test/MLPipelineTester.py --ml_lib snap
  # verify that for single chunk training, we get _exactly_ the same prediction as Snap Boost
  - python test/MLPipelineBoostVerify.py --ml_lib snap --dataset_path test/data/train.higgs.csv --dataset_test_path test/data/test.higgs.csv --chunk_size 100 --verify --ml_obj logloss --ml_model_options objective=logloss,num_round=1,min_max_depth=4,max_max_depth=6,n_threads=1,random_state=42
notifications:
  email:
    recipients:
      - nio@zurich.ibm.com
    on_success: never # default: change
    on_failure: always # default: always
